stages:
  download_data:
    cmd: python download_data.py
    deps:
      - download_data.py
      - params.yaml
    outs:
      - data/batches

  train:
    cmd: python train.py
    deps:
      - train.py
      - data.py
      - model.py
      - config.py
      - params.yaml
      - utils.py
      - train_utils.py
    outs:
      - trained_model.pth

  evaluate:
    cmd: python evaluate.py
    deps:
      - evaluate.py
      - data.py
      - trained_model.pth
      - params.yaml
      - data/batches/test_batch
    metrics:
      - metrics.json

